name: form-ms-dev

services:
  forms-db:
    container_name: forms_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=forms-db

  forms-ms:
    build: ./
    image: forms-ms
    volumes:
      - ./src:/usr/src/app/src
    ports:
      # SERVER:DOCKER
      - 3001:3001
    command: npm run compose:start
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:123456@forms-db:5432/forms-db?schema=public
    depends_on:
      - forms-db
